name: Daily Bug Digest Email

on:
  schedule:
    - cron: '0 1 * * *'
  workflow_dispatch:

jobs:
  email-notifier:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.x

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Run Email Notifier
        env:
          EMAIL_USER: ${{ secrets.EMAIL_USER }}
          EMAIL_PASS: ${{ secrets.EMAIL_PASS }}
        run: python src/dashboard/bug_email_notifier.py
