name: Three Days Update

on:
  schedule:
    - cron: '0 1 * * *' 
  workflow_dispatch:

jobs:
  run-pipeline:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Run pipeline
        run: python src/data_processing/run_pipeline.py

      - name: Commit data outputs
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add data/*.csv data/bug_data.db
          if git diff --cached --quiet; then
            echo "No data changes to commit"
          else
            git commit -m "Update data CSV files and database"
            git remote set-url origin "https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}.git"
            git push origin HEAD:${{ github.ref }}
          fi

      - name: Upload data outputs
        uses: actions/upload-artifact@v4
        with:
          name: pipeline-data
          path: |
            data/*.csv
            data/bug_data.db
